### ISSUE TITLE
Suma de plata incorecta

### ISSUE THREAD

**Issue by rockredbones** [g4b1nagy/hipmenu-checklist#3]
Pentru persoanele din lista care au mai multe produse adaugate in cos, in plugin este afisata doar valoarea primului produs, nu valoarea totala. 

Testat pe: 
- Chrome Version: 47.0.2526.80 (64-bit)
- Mac OS X Yosemite (10.10.5)

**Comment by g4b1nagy** [comment]
Mersi pentru observatie :) Am rezolvat mai multe probleme in ultima versiune, asa ca o sa te rog sa faci un update => https://chrome.google.com/webstore/detail/hipmenu-checklist/fdbmfcgckbobgefkgcbkdcjejcnoahag
